/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wxsafe.back.action;

import java.io.File;
import java.io.FileInputStream;
import java.io.OutputStream;
import java.sql.Connection;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wxsafe.ccy.dao.DataSourseFactory;
import com.wxsafe.ccy.method.MaterialMethods;

/**
 * @author : CaoChenYin
 * 
 * @Class : Download
 * 
 * @description : 处理下载附件请求
 * 
 * @date : 2009/03/27
 */
public class Download extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		File file = null;
		String maAffix = request.getParameter("maAffix");
		file = new File(this.getServlet().getServletContext().getRealPath("/")
				+ maAffix);
		int index = maAffix.lastIndexOf("/");

		String filename = maAffix.substring(index + 1, maAffix.length());
	
		if (file.exists()) {
			try {
				
				byte b[] = new byte[500];
				
				response.setHeader("Content-disposition",
						"attachment;filename=" + filename); 
				response.setContentType("text/plain");
				long fileLength = file.length();
				String length = String.valueOf(fileLength);
				response.setHeader("Content_Length", length); 
				FileInputStream in = new FileInputStream(file);
				OutputStream o = response.getOutputStream();
				int n = 0;
				while ((n = in.read(b)) != -1) {
					o.write(b, 0, n); 
				}
				in.close();
				o.close();
				String getID = request.getParameter("maID");
				if (getID != null) {
					int maID = Integer.parseInt(getID);
					Connection conn = null;
					conn = DataSourseFactory.getDataSource().getConnection();
					MaterialMethods mm = new MaterialMethods(conn);
					mm.down(maID);
				}
			} catch (Exception e) {
			}
		}

		return null;

	}
}