/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wxsafe.ccy.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 03-25-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="DoForm"
 */
public class DoForm extends ActionForm {
	/**
	 * 
	 */

	/*
	 * Generated Methods
	 */

	private int[] maIDs;
	private int[] isIDs;
	private int[] userIDs;
	private int deleteModel;

	private int typeID;

	private String keyword;

	private int page;

	public int[] getMaIDs() {
		return maIDs;
	}

	public void setMaIDs(int[] maIDs) {
		this.maIDs = maIDs;
	}

	public int[] getIsIDs() {
		return isIDs;
	}

	public void setIsIDs(int[] isIDs) {
		this.isIDs = isIDs;
	}

	public int[] getUserIDs() {
		return userIDs;
	}

	public void setUserIDs(int[] userIDs) {
		this.userIDs = userIDs;
	}

	public int getDeleteModel() {
		return deleteModel;
	}

	public void setDeleteModel(int deleteModel) {
		this.deleteModel = deleteModel;
	}

	public int getTypeID() {
		return typeID;
	}

	public void setTypeID(int typeID) {
		this.typeID = typeID;
	}

	public String getKeyword() {
		return keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public int getPage() {
		return page;
	}

	public void setPage(int page) {
		this.page = page;
	}


	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}