/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wxsafe.ccy.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

/**
 * MyEclipse Struts Creation date: 03-25-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="MaterialForm"
 */
public class MaterialForm extends ActionForm {
	/**
	 * 
	 */
	

	/*
	 * Generated Methods
	 */
	
	private String operation;
	
	public String getOperation() {
		return operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	private int maID;

	private String maName;

	private String maCode;

	private int maType;

	private String maBranch;

	private String maOrigin;

	private String maOtherName;

	private String maFormat;

	private int maPrice1;

	private int maPrice2;

	private String maBrand;

	private String maGrade;

	private String maPart;

	private String maTrait;

	private String maEffect;

	private String maEnvironment;

	private FormFile pic;

	private String maPicPath;

	private FormFile affix;

	private String maAffix;
	
	private int isRecommend;

	private int downCount;

	public FormFile getAffix() {
		return affix;
	}

	public void setAffix(FormFile affix) {
		this.affix = affix;
	}

	public String getMaAffix() {
		return maAffix;
	}

	public void setMaAffix(String maAffix) {
		this.maAffix = maAffix;
	}

	public int getIsRecommend() {
		return isRecommend;
	}

	public void setIsRecommend(int isRecommend) {
		this.isRecommend = isRecommend;
	}

	public int getDownCount() {
		return downCount;
	}

	public void setDownCount(int downCount) {
		this.downCount = downCount;
	}



	public FormFile getPic() {
		return pic;
	}

	public void setPic(FormFile pic) {
		this.pic = pic;
	}

	public int getMaID() {
		return maID;
	}

	public void setMaID(int maID) {
		this.maID = maID;
	}

	public String getMaName() {
		return maName;
	}

	public void setMaName(String maName) {
		this.maName = maName;
	}

	public String getMaCode() {
		return maCode;
	}

	public void setMaCode(String maCode) {
		this.maCode = maCode;
	}

	public int getMaType() {
		return maType;
	}

	public void setMaType(int maType) {
		this.maType = maType;
	}

	public String getMaBranch() {
		return maBranch;
	}

	public void setMaBranch(String maBranch) {
		this.maBranch = maBranch;
	}

	public String getMaOrigin() {
		return maOrigin;
	}

	public void setMaOrigin(String maOrigin) {
		this.maOrigin = maOrigin;
	}

	public String getMaOtherName() {
		return maOtherName;
	}

	public void setMaOtherName(String maOtherName) {
		this.maOtherName = maOtherName;
	}

	public String getMaFormat() {
		return maFormat;
	}

	public void setMaFormat(String maFormat) {
		this.maFormat = maFormat;
	}

	public int getMaPrice1() {
		return maPrice1;
	}

	public void setMaPrice1(int maPrice1) {
		this.maPrice1 = maPrice1;
	}

	public int getMaPrice2() {
		return maPrice2;
	}

	public void setMaPrice2(int maPrice2) {
		this.maPrice2 = maPrice2;
	}

	public String getMaBrand() {
		return maBrand;
	}

	public void setMaBrand(String maBrand) {
		this.maBrand = maBrand;
	}

	public String getMaGrade() {
		return maGrade;
	}

	public void setMaGrade(String maGrade) {
		this.maGrade = maGrade;
	}

	public String getMaPart() {
		return maPart;
	}

	public void setMaPart(String maPart) {
		this.maPart = maPart;
	}

	public String getMaTrait() {
		return maTrait;
	}

	public void setMaTrait(String maTrait) {
		this.maTrait = maTrait;
	}

	public String getMaEffect() {
		return maEffect;
	}

	public void setMaEffect(String maEffect) {
		this.maEffect = maEffect;
	}

	public String getMaEnvironment() {
		return maEnvironment;
	}

	public void setMaEnvironment(String maEnvironment) {
		this.maEnvironment = maEnvironment;
	}

	public String getMaPicPath() {
		return maPicPath;
	}

	public void setMaPicPath(String maPicPath) {
		this.maPicPath = maPicPath;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	// public ActionErrors validate(ActionMapping mapping,
	// HttpServletRequest request) {
	// // TODO Auto-generated method stub
	// return null;
	// }
	//
	// /**
	// * Method reset
	// *
	// * @param mapping
	// * @param request
	// */
	// public void reset(ActionMapping mapping, HttpServletRequest request) {
	// // TODO Auto-generated method stub
	// }
}