/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wxsafe.front.action;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wxsafe.ccy.dao.DataSourseFactory;
import com.wxsafe.ccy.dto.MaterialDto;
import com.wxsafe.ccy.dto.PageDto;
import com.wxsafe.ccy.dto.ReviewDto;
import com.wxsafe.ccy.dto.TypeDto;
import com.wxsafe.ccy.form.DetaiForm;
import com.wxsafe.ccy.method.MaterialMethods;
import com.wxsafe.ccy.method.ReviewMetheds;
import com.wxsafe.ccy.method.TypeMethods;

/**
 * @author : CaoChenYin
 * 
 * @Class : DetailAction
 * 
 * @description : 处理明细显示材料信息请求
 * 
 * @date : 2009/04/22
 */
public class DetailAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String flag = "fail";
		DetaiForm detailForm = (DetaiForm) form;
		// 获取材料ID
		int maID = detailForm.getMaID();
		Connection conn = null;
		try {
			conn = DataSourseFactory.getDataSource().getConnection();
			MaterialMethods mm = new MaterialMethods(conn);
			// 浏览次数+1
			mm.click(maID);
			MaterialDto maDto = new MaterialDto();
			// 获取材料信息保存在dto中
			maDto = mm.selectMaterial(maID);
			// 获取该材料的分类ID
			int typeID = maDto.getMaType();
			request.setAttribute("ma", maDto);
			TypeMethods tm = new TypeMethods(conn);
			// 获取分类信息
			TypeDto typeDto = tm.selectType(typeID);
			request.setAttribute("type", typeDto);
			// 获取该分类下的下载排行前10
			List<MaterialDto> topDown = mm.selectTopDown(typeID);
			request.setAttribute("topDown", topDown);
			// 获取上一个材料
			MaterialDto back = mm.selectBackNext(maID, typeID, 1);
			request.setAttribute("back", back);
			// 获取下一个材料
			MaterialDto next = mm.selectBackNext(maID, typeID, 0);
			request.setAttribute("next", next);
			// 获取该分类所有父分类
			List<TypeDto> allType = tm.selectAllParentType(typeID);
			request.setAttribute("allType", allType);
			// 获得评论页
			int page = detailForm.getPage();
			ReviewMetheds rm = new ReviewMetheds(conn);
			// 获得评论总条数
			int count = rm.getReviewCount(maID);
			request.setAttribute("count", count);
			PageDto dto = new PageDto(count, page, 5);
			//获得当前页评论list
			List<ReviewDto> reList = rm.listReviewByID(maID, dto);
			request.setAttribute("review", reList);
			request.setAttribute("count", count);
			request.setAttribute("page", dto.getPage());
			request.setAttribute("pages", dto.getPages());

			conn.close();
			flag = "success";
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward(flag);
	}
}