/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wxsafe.front.action;

import java.sql.Connection;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wxsafe.ccy.common.StringUtil;
import com.wxsafe.ccy.dao.DataSourseFactory;
import com.wxsafe.ccy.form.ReviewForm;
import com.wxsafe.ccy.method.ReviewMetheds;

/**
 * @author : CaoChenYin
 * 
 * @Class : SendReviewAaction
 * 
 * @description : 处理发表评论请求
 * 
 * @date : 2009/04/22
 */
public class SendReviewAaction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ReviewForm reviewForm = (ReviewForm) form;
		String flag = "fail";
		Connection conn = null;
		try {
			conn = DataSourseFactory.getDataSource().getConnection();
			ReviewMetheds rm = new ReviewMetheds(conn);
		
			String msg=reviewForm.getReMessage();
			// 转换特殊字符串
			msg=StringUtil.CheckSpecialChar(msg);
			// 换行转化
			msg=StringUtil.CheckLineChar(msg);
			reviewForm.setReMessage(msg);
		
			// 发表评论
			boolean bool = rm.addReview(reviewForm);
			conn.close();
			// 发表成功后，返回当前页面
			if (bool) {
				request.setAttribute("forward", "/detail.do?maID="
						+ reviewForm.getMaID());
				flag = "success";
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward(flag);
	}
}